[package]
name = "oxide-api-prototype"
version = "0.1.0"
authors = ["David Pacheco <dap@oxidecomputer.com>"]
edition = "2018"
default-run = "oxide-controller"

[dependencies]
async-trait = "0.1.24"
chrono = { version = "0.4", features = [ "serde" ] }
clap = "2"
futures = "0.3.1"
http = "0.2.0"
dropshot = { path = "dropshot" }
hyper = "0.13"
serde = { version = "1.0", features = [ "derive" ] }
tokio = { version = "0.2", features = [ "full" ] }
toml = "0.5.6"
uuid = { version = "0.8", features = [ "serde", "v4" ] }

[dependencies.slog]
version = "2.5"
features = [ "max_level_trace", "release_max_level_debug" ]

[workspace]
members = [".", "dropshot", "dropshot/dropshot_endpoint" ]
default-members = [".", "dropshot", "dropshot/dropshot_endpoint" ]

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
