[package]
name = "oxide-api-prototype"
version = "0.1.0"
authors = ["David Pacheco <dap@oxidecomputer.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.24"
bytes = "0.5.4"
chrono = "0.4"
futures = "0.3.1"
http = "0.2.0"
hyper = "0.13"
openapi = { path = "lib/openapi" }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
serde_urlencoded = "0.6"
slog = "2.5"
slog-async = "2.4"
slog-term = "2.5"
tokio = { version = "0.2", features = [ "full" ] }
toml = "0.5.6"
url = "^2.1"
uuid = { version = "0.8", features = [ "serde", "v4" ] }
