[package]
name = "oxide-api-prototype"
version = "0.1.0"
authors = ["David Pacheco <dap@oxidecomputer.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.24"
chrono = { version = "0.4", features = [ "serde" ] }
futures = "0.3.1"
hostname = "0.3.0"
http = "0.2.0"
httpapi = { path = "lib/httpapi" }
hyper = "0.13"
openapi = { path = "lib/openapi" }
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
slog = { version = "2.5", features = [ "max_level_trace", "release_max_level_debug" ] }
slog-async = "2.4"
slog-bunyan = "2.2"
slog-json = "2.3"
slog-term = "2.5"
tokio = { version = "0.2", features = [ "full" ] }
toml = "0.5.6"

[workspace]
members = [".", "lib/httpapi", "lib/openapi"]
default-members = [".", "lib/httpapi", "lib/openapi"]
