[package]
name = "oxide-api-prototype"
version = "0.1.0"
authors = ["David Pacheco <dap@oxidecomputer.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.24"
clap = "2"
futures = "0.3.1"
http = "0.2.0"
dropshot = { path = "lib/dropshot" }
hyper = "0.13"
openapi = { path = "lib/openapi" }
serde = { version = "1.0", features = [ "derive" ] }
slog = { version = "2.5", features = [ "max_level_trace", "release_max_level_debug" ] }
tokio = { version = "0.2", features = [ "full" ] }
toml = "0.5.6"

[workspace]
members = [".", "lib/dropshot", "lib/openapi"]
default-members = [".", "lib/dropshot", "lib/openapi"]
