# This manifest describes packages which will be ingested by
# the "omicron-package" tool - instructing how they should be
# build, thrown into a tarball, and installed on the target system.

# Path to SMF manifest directory
smf = "smf"

# Package name
[package.omicron-sled-agent]
# Binary name
rust.binary_name = "sled-agent"
# Service name (subdirectory within "smf")
service_name = "sled-agent"
# (Optional) Indicates this is a bootstrapping service, and should be installed.
# Points to the SMF manifest within this package.
bootstrap = "manifest.xml"

[package.omicron-nexus]
rust.binary_name = "nexus"
service_name = "nexus"
[[package.omicron-nexus.zone.paths]]
from = "/opt/ooce/pgsql-13/lib/amd64"
to = "/opt/ooce/pgsql-13/lib/amd64"

[package.oximeter-collector]
rust.binary_name = "oximeter"
service_name = "oximeter"
zone.paths = []

[package.propolis-server]
rust.binary_name = "propolis-server"
service_name = "propolis-server"
zone.paths = []
# (Optional) List of binary blobs to be downloaded from S3.
blobs = [ "alpine.iso", "OVMF_CODE.fd" ]

[package.cockroachdb]
service_name = "cockroachdb"
[[package.cockroachdb.zone.paths]]
from = "cockroachdb"
to = "/opt/oxide/cockroachdb"
[[package.cockroachdb.zone.paths]]
from = "common/src/sql"
to = "/opt/oxide/cockroachdb/sql"
