#
# We use nightly for a few unstable features:
#
# - the "asm" feature for dtrace probes (within Propolis)
# - the "configurable_env" feature (stabilized in 1.56)
#
# We specify a specific, known-good nightly to avoid regular breakage.
# Once the above features stabilize, we should switch back to "stable".
#

[toolchain]
# NOTE: This toolchain is also specified within .github/workflows/rust.yml
# If you update it here, update that file too.
channel = "nightly-2021-09-03"
profile = "default"
