# Identifier for this instance of Nexus
id = "e6bff1ff-24fb-49dc-a54e-c6a350cd4d6c"

[database]
# URL for connecting to the database
url = "postgresql://root@127.0.0.1:32221/omicron?sslmode=disable"

[dropshot_external]
bind_address = "127.0.0.1:12220"

[dropshot_internal]
bind_address = "127.0.0.1:12221"

[log]
level = "info"
mode = "stderr-terminal"
