[package]
name = "crucible-agent-client"
version = "0.0.0"
edition = "2018"

[dependencies]
anyhow = "1"
percent-encoding = "2.1"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "0.8", features = ["serde", "v4"] }

