# Configuration for propolis server.
#
# Refer to https://github.com/oxidecomputer/propolis#readme
# for more detail on the config format.

bootrom = "/opt/oxide/propolis-server/blob/OVMF_CODE.fd"

# XXX # [block_dev.bd0]
# XXX # type = "file"
# XXX # path = "/opt/oxide/propolis-server/blob/alpine.iso"
# XXX # readonly = "true"
# XXX # 
# XXX # [dev.block0]
# XXX # driver = "pci-virtio-block"
# XXX # block_dev = "bd0"
# XXX # pci-path = "0.4.0"

# NOTE: This VNIC is here for reference, but VNICs are typically managed by the
# Sled Agent.

# [dev.net0]
# driver = "pci-virtio-viona"
# vnic = "vnic_prop0"
# pci-path = "0.5.0"
