# RSS (Rack Setup Service) "stand-in" configuration.

[[request]]
sled_address = "127.0.0.1:12345"

# TODO: Failing; need to supply crucible image. See package-manifest.toml.
#
# [[request.partition]]
# zpool_uuid = "d462a7f7-b628-40fe-80ff-4e4189e2d62b"
# address = "[fd00:1234::]:32345"
# partition_kind.type = "crucible"

# TODO: Add a partition for Clickhouse too

[[request.partition]]
zpool_uuid = "d462a7f7-b628-40fe-80ff-4e4189e2d62b"
address = "[fd00:1234::5]:32221"
partition_kind.type = "cockroach_db"
partition_kind.all_addresses = [
  "[fd00:1234::5]:32221",
]

[[request.service]]
name = "nexus"
address = "[fd00:1234::7]:32221"

# [[request.service]]
# name = "oximeter"
# address = "[fd00:1234::6]:12223"
