# Sled Agent Configuration

id = "fb0f7546-4d46-40ca-9d56-cbb810684ca7"

bootstrap_address = "[::]:12346"
nexus_address = "127.0.0.1:12221"
sled_address = "127.0.0.1:12345"

# Address of the Sled Agent itself
[dropshot]
bind_address = "127.0.0.1:12345"

[log]
level = "info"
mode = "stderr-terminal"


# TODO: A file-backed zpool can be manually created with the following:
# $ truncate -s 10GB testpool.vdev
# $ zpool create d462a7f7-b628-40fe-80ff-4e4189e2d62b testpool.vdev
#
# Plus adding the "\-\-zpools d462a7f7-b628-40fe-80ff-4e4189e2d62b" argument
# when initializing the sled agent.
# zpools = [ "d462a7f7-b628-40fe-80ff-4e4189e2d62b" ]
