# Sled Agent Configuration

id = "fb0f7546-4d46-40ca-9d56-cbb810684ca7"

bootstrap_address = "[::]:12346"
# Internal address of Nexus
nexus_address = "[fd00:1234::7]:12221"

# TODO: A file-backed zpool can be manually created with the following:
# $ truncate -s 10GB testpool.vdev
# $ zpool create d462a7f7-b628-40fe-80ff-4e4189e2d62b testpool.vdev
#
# Plus adding the "\-\-zpools d462a7f7-b628-40fe-80ff-4e4189e2d62b" argument
# when initializing the sled agent.
zpools = [ "d462a7f7-b628-40fe-80ff-4e4189e2d62b" ]

# Address of the Sled Agent itself
#
# XXX: With the movement to zones, we no longer can use localhost addresses,
# as Nexus (within a Zone) is effectively "on a different machine" from the
# sled agent.
#
# This address may be allocated with the following command:
#
# pfexec ipadm create-addr -t -T static -a 192.168.1.201 $(dladm show-phys -p -o LINK)/sled4
# |      |                                               |
# Please |                                               |
#        Create a temporary static address               |
#                                                        On whatever physical datalink I have
[dropshot]
bind_address = "192.168.1.201:12345"

[log]
level = "info"
mode = "stderr-terminal"


