#
# Configuration for GitHub-based CI, based on the stock GitHub Rust config.
#
name: Rust

on: [ push, pull_request ]

jobs:
  check-style:
    runs-on: ubuntu-18.04
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
    - name: Check style
      run: cargo fmt -- --check

  clippy-lint:
    runs-on: ubuntu-18.04
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
    - name: Run Clippy Lints
      run: >
        # TODO: Migrate these options to a config file in the workspace,
        # once https://github.com/rust-lang/rust-clippy/issues/6625 is resolved.
        cargo clippy -- -D warnings
        # TODO: Fixed by https://github.com/rust-lang/rust-clippy/issues/6344
        # Fix exists on nightly, not on stable.
        -A clippy::field_reassign_with_default
        # Many functions (internal to OXCP) propagate result types
        # as an expected transformation, even when an error case is not possible.
        # Avoiding this lint is intentional, as it avoids boilerplate.
        -A clippy::unnecessary_wraps

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-18.04, windows-2019, macos-10.15 ]
    steps:
    # actions/checkout@v2
    - uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b
    - name: Build
      run: cargo build --tests --verbose
    - name: Run tests
      run: cargo test --verbose
